import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import type { EcosystemOrganization, EcosystemProgram } from "../src/types/ecosystem";

const CHECKED_AT = "2026-08-24";
const PROGRAM_REVIEW_AT = "2026-09-07";
const DIRECTORY_REVIEW_AT = "2026-12-22";
const organizationsPath = resolve(process.cwd(), "src/data/ecosystem/organizations.json");
const programsPath = resolve(process.cwd(), "src/data/ecosystem/programs.json");

const singaporeLocation = (id: string, name: string, source: string) => ({
  id: `${id}-singapore`,
  role: "headquarters" as const,
  label: `${name} — Singapore`,
  address: null,
  city: "Singapore",
  district: null,
  state: "Singapore",
  postalCode: null,
  marketCode: "SG" as const,
  countryCode: "SG",
  coordinates: { lat: 1.3521, lng: 103.8198 },
  precision: "city" as const,
  evidenceUrl: source,
  verifiedAt: CHECKED_AT,
});

const organizerSeeds: EcosystemOrganization[] = [
  {
    id: "astar-singapore",
    kind: "organization",
    name: "A*STAR",
    aliases: ["Agency for Science, Technology and Research"],
    categories: ["government_agency", "incubator"],
    description: "Singapore's public-sector research agency, providing scientific facilities, commercialization support, and capability-upgrading programs for technology companies and SMEs.",
    status: "active",
    publicationState: "published",
    website: "https://www.a-star.edu.sg/",
    logoUrl: "https://www.google.com/s2/favicons?domain=a-star.edu.sg&sz=128",
    serviceMarkets: [{ marketCode: "SG", serviceMode: "hybrid" }],
    sectors: ["deeptech", "research and development", "biotech", "manufacturing"],
    stages: ["idea", "pre_seed", "seed", "series_a", "growth"],
    supportCapabilities: ["labs", "mentorship", "grants", "ip_support"],
    applicationUrl: "https://www.a-star.edu.sg/enterprise/innovation-offerings/programmes-for-smes",
    affiliations: ["Government of Singapore"],
    registrations: [],
    managedVehicles: [],
    locations: [singaporeLocation("astar-singapore", "A*STAR", "https://www.a-star.edu.sg/enterprise/partnership-collaboration")],
    evidence: [{
      url: "https://www.a-star.edu.sg/enterprise/partnership-collaboration",
      title: "Partnership & Collaboration",
      publisher: "A*STAR",
      sourceClass: "official_website",
      checkedAt: CHECKED_AT,
      supports: ["current enterprise support", "commercialization programs", "laboratory and technical capabilities"],
    }],
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: DIRECTORY_REVIEW_AT,
  },
  {
    id: "sginnovate",
    kind: "organization",
    name: "SGInnovate",
    aliases: [],
    categories: ["government_agency", "accelerator", "vc_firm"],
    description: "A Singapore government-owned deep-tech investor and ecosystem platform providing venture funding, talent programs, founder support, and industry connections.",
    status: "active",
    publicationState: "published",
    website: "https://www.sginnovate.com/",
    logoUrl: "https://www.google.com/s2/favicons?domain=sginnovate.com&sz=128",
    serviceMarkets: [{ marketCode: "SG", serviceMode: "hybrid" }],
    sectors: ["deeptech", "biotech", "artificial intelligence", "climate"],
    stages: ["pre_seed", "seed", "series_a"],
    supportCapabilities: ["seed_funding", "mentorship", "market_access", "investor_access"],
    applicationUrl: "https://www.sginnovate.com/startup-growth-funding",
    affiliations: ["Government of Singapore"],
    registrations: [],
    managedVehicles: [],
    locations: [singaporeLocation("sginnovate", "SGInnovate", "https://www.sginnovate.com/startup-growth-funding")],
    evidence: [{
      url: "https://www.sginnovate.com/startup-growth-funding",
      title: "Startup Growth & Funding",
      publisher: "SGInnovate",
      sourceClass: "official_website",
      checkedAt: CHECKED_AT,
      supports: ["current deep-tech startup support", "funding", "talent programs"],
    }],
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: DIRECTORY_REVIEW_AT,
  },
  {
    id: "temasek-life-sciences-accelerator",
    kind: "organization",
    name: "Temasek Life Sciences Accelerator",
    aliases: ["TLA"],
    categories: ["accelerator", "incubator", "vc_firm"],
    description: "A Singapore life-sciences incubator and early-stage investor commercializing agrifood, biotech, sustainability, and health innovations through venture building and specialist support.",
    status: "active",
    publicationState: "published",
    website: "https://www.tla.com.sg/",
    logoUrl: "https://www.google.com/s2/favicons?domain=tla.com.sg&sz=128",
    foundedYear: 2016,
    serviceMarkets: [{ marketCode: "SG", serviceMode: "hybrid" }],
    sectors: ["biotech", "agritech", "foodtech", "healthcare", "climate"],
    stages: ["idea", "pre_seed", "seed", "series_a"],
    supportCapabilities: ["labs", "seed_funding", "mentorship", "ip_support", "investor_access"],
    investmentThesis: "Incubate, nurture, and grow disruptive life-science innovations into early-stage companies.",
    investmentPreference: "lead",
    applicationUrl: "https://www.tla.com.sg/",
    affiliations: ["Temasek Life Sciences Laboratory", "Vertex Venture Holdings"],
    registrations: [],
    managedVehicles: ["The Lifesciences Innovation Fund"],
    locations: [singaporeLocation("temasek-life-sciences-accelerator", "Temasek Life Sciences Accelerator", "https://www.tll.org.sg/")],
    evidence: [{
      url: "https://www.tll.org.sg/",
      title: "Temasek Life Sciences Laboratory — Innovation Framework",
      publisher: "Temasek Life Sciences Laboratory",
      sourceClass: "official_website",
      checkedAt: CHECKED_AT,
      supports: ["current accelerator identity", "venture building", "life-science commercialization"],
    }],
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: DIRECTORY_REVIEW_AT,
  },
  {
    id: "trive-venture-capital",
    kind: "organization",
    name: "TRIVE Venture Capital",
    aliases: ["TRIVE", "TRIVE Ventures"],
    categories: ["vc_firm", "venture_studio"],
    description: "A Singapore-licensed early-stage venture manager backing Southeast Asian founders in essential technology, Web3, artificial intelligence, food, mobility, education, and healthcare.",
    status: "active",
    publicationState: "published",
    website: "https://www.trive.vc/",
    logoUrl: "https://www.google.com/s2/favicons?domain=trive.vc&sz=128",
    serviceMarkets: [{ marketCode: "SG", serviceMode: "hybrid" }],
    sectors: ["software", "artificial intelligence", "web3", "foodtech", "mobility", "healthcare"],
    stages: ["pre_seed", "seed", "series_a"],
    supportCapabilities: ["seed_funding", "mentorship", "market_access", "investor_access"],
    investmentThesis: "Early-stage technology and essential-economy companies across Southeast Asia, with separate Web3 and venture-building strategies.",
    investmentRange: { min: 200000, max: 5000000, currency: "USD", asStated: "USD 200,000 average for TRIVE Digital; USD 1–5 million for TRIVE Ventures" },
    investmentPreference: "both",
    portfolioUrl: "https://www.trive.vc/",
    applicationUrl: "https://www.trive.vc/",
    affiliations: [],
    registrations: [{ authority: "Monetary Authority of Singapore", registrationNumber: "MAS FID 200852", vehicleName: "TRIVE VENTURE CAPITAL PTE. LTD." }],
    managedVehicles: ["TRIVE Ventures", "TRIVE Digital"],
    locations: [singaporeLocation("trive-venture-capital", "TRIVE Venture Capital", "https://eservices.mas.gov.sg/fid/institution/detail/200852-TRIVE-VENTURE-CAPITAL-PTE-LTD")],
    evidence: [
      {
        url: "https://eservices.mas.gov.sg/fid/institution/detail/200852-TRIVE-VENTURE-CAPITAL-PTE-LTD",
        title: "TRIVE Venture Capital Pte. Ltd.",
        publisher: "Monetary Authority of Singapore",
        sourceClass: "regulator",
        checkedAt: CHECKED_AT,
        supports: ["current venture-capital fund-management licence", "Singapore office", "official website"],
      },
      {
        url: "https://www.trive.vc/",
        title: "TRIVE — Venture Capital Southeast Asia",
        publisher: "TRIVE Venture Capital",
        sourceClass: "official_website",
        checkedAt: CHECKED_AT,
        supports: ["current investment strategies", "published cheque ranges", "founder pitch path", "portfolio"],
      },
    ],
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: DIRECTORY_REVIEW_AT,
  },
];

const officialEvidence = (url: string, title: string, publisher: string, supports: string[]) => [{
  url,
  title,
  publisher,
  sourceClass: "official_website" as const,
  checkedAt: CHECKED_AT,
  supports,
}];

const programSeeds: EcosystemProgram[] = [
  {
    id: "entrepass-singapore",
    kind: "program",
    name: "EntrePass",
    aliases: [],
    programType: "government_scheme",
    organizerIds: ["enterprise-singapore"],
    description: "Singapore's continuously available work-pass route for eligible foreign founders establishing and operating a venture-backed or innovative technology business.",
    publicationState: "published",
    deliveryMode: "remote",
    locationIds: [],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: ["SG"],
    sectors: ["technology"],
    stages: ["idea", "pre_seed", "seed"],
    eligibility: "Foreign founders of a Singapore private limited company that is venture-backed or owns innovative technologies and who meet at least one published entrepreneur, innovator, or investor criterion.",
    benefits: ["Permission to start and operate an eligible Singapore business", "Access to Singapore's startup community"],
    equityTerms: "No equity stated",
    applicationUrl: "https://www.mom.gov.sg/passes-and-permits/entrepass/apply-for-a-pass",
    rolling: true,
    evidence: officialEvidence("https://www.mom.gov.sg/passes-and-permits/entrepass/apply-for-a-pass", "Apply for an EntrePass", "Singapore Ministry of Manpower", ["online application available", "fees", "processing time"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "global-tech-talent-alliance",
    kind: "program",
    name: "Global Tech Talent Alliance",
    aliases: ["GTTA"],
    programType: "government_scheme",
    organizerIds: ["enterprise-singapore"],
    description: "An ongoing Enterprise Singapore pathway giving Singapore-based companies access to vetted tech-talent service providers and preferential rates in India and Vietnam.",
    publicationState: "published",
    deliveryMode: "remote",
    locationIds: [],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: ["SG"],
    sectors: ["technology"],
    stages: ["pre_seed", "seed", "series_a", "series_b_plus", "growth"],
    eligibility: "Singapore-based companies seeking to build technology teams in India or Vietnam.",
    benefits: ["Curated talent-provider panel", "Preferential recruitment and team-building rates", "International market-entry support"],
    equityTerms: "No equity stated",
    applicationUrl: "https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/innovation-talent/global-tech-talent-alliance",
    rolling: true,
    evidence: officialEvidence("https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/innovation-talent/global-tech-talent-alliance", "Global Tech Talent Alliance", "Enterprise Singapore", ["current provider list", "eligibility", "how to apply"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "tech-at-sg",
    kind: "program",
    name: "Tech@SG",
    aliases: [],
    programType: "government_scheme",
    organizerIds: ["enterprise-singapore"],
    description: "An ongoing endorsement scheme helping qualifying fast-growing Singapore technology companies secure Employment Passes for critical international core-team hires.",
    publicationState: "published",
    deliveryMode: "remote",
    locationIds: [],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: ["SG"],
    sectors: ["technology", "deeptech"],
    stages: ["series_a", "series_b_plus", "growth"],
    eligibility: "Qualifying Singapore-incorporated technology companies funded by a programme-recognised investment firm and meeting the published ownership, funding, and employee criteria.",
    benefits: ["Government endorsement for up to ten new Employment Passes over two years"],
    equityTerms: "No equity stated",
    applicationUrl: "https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/innovation-talent/tech-at-sg",
    rolling: true,
    evidence: officialEvidence("https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/innovation-talent/tech-at-sg", "Tech@SG", "Enterprise Singapore", ["apply-now path", "eligibility", "Employment Pass benefit"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "t-up-singapore",
    kind: "program",
    name: "Technology for Enterprise Capability Upgrading (T-Up)",
    aliases: ["T-Up"],
    programType: "government_scheme",
    organizerIds: ["astar-singapore", "enterprise-singapore"],
    description: "An ongoing program that seconds A*STAR scientists and engineers into eligible Singapore companies for up to two years to deliver R&D and product-development projects.",
    publicationState: "published",
    deliveryMode: "hybrid",
    locationIds: ["astar-singapore-singapore"],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: ["SG"],
    sectors: ["research and development", "deeptech", "manufacturing"],
    stages: ["seed", "series_a", "series_b_plus", "growth"],
    eligibility: "Eligible local SMEs or larger local enterprises able to finance and complete an approved R&D or innovation project and meeting the published size and ownership requirements.",
    benefits: ["A*STAR scientist or engineer secondment for up to two years", "Up to 70% grant support for qualifying costs"],
    equityTerms: "No equity stated",
    applicationUrl: "https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/innovation-talent/technology-for-enterprise-capability-upgrading",
    rolling: true,
    evidence: officialEvidence("https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/innovation-talent/technology-for-enterprise-capability-upgrading", "Technology for Enterprise Capability Upgrading", "Enterprise Singapore", ["registration path", "eligibility", "secondment benefit"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "gia-acceleration-programmes",
    kind: "program",
    name: "GIA Acceleration Programmes",
    aliases: ["Global Innovation Alliance Acceleration Programmes"],
    programType: "accelerator_cohort",
    organizerIds: ["enterprise-singapore"],
    description: "A portfolio of international market-entry accelerators offering workshops, mentorship, and connections with potential customers and partners in major innovation hubs.",
    publicationState: "published",
    deliveryMode: "hybrid",
    locationIds: [],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: ["SG"],
    sectors: ["technology"],
    stages: ["seed", "series_a", "series_b_plus", "growth"],
    eligibility: "Singapore-based startups and technology SMEs seeking overseas market entry, subject to the requirements of an open destination programme.",
    benefits: ["Market-entry workshops", "Mentorship", "Customer and partner introductions"],
    equityTerms: "No equity stated",
    applicationUrl: "https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/market-access-and-networks/global-innovation-alliance/acceleration-programmes",
    rolling: true,
    evidence: officialEvidence("https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/market-access-and-networks/global-innovation-alliance/acceleration-programmes", "GIA Acceleration Programmes", "Enterprise Singapore", ["ongoing destination programmes", "program benefits", "application links"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "gia-co-innovation-programmes",
    kind: "program",
    name: "GIA Co-Innovation Programmes",
    aliases: ["Global Innovation Alliance Co-Innovation Programmes"],
    programType: "grant",
    organizerIds: ["enterprise-singapore"],
    description: "A continuously refreshed portfolio of bilateral and multilateral calls funding Singapore companies and overseas partners to co-develop market-oriented R&D products and solutions.",
    publicationState: "published",
    deliveryMode: "hybrid",
    locationIds: [],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: ["SG"],
    sectors: ["research and development", "technology"],
    stages: ["seed", "series_a", "series_b_plus", "growth"],
    eligibility: "A financially viable Singapore-registered lead company with at least 30% local ownership and an eligible overseas project partner for a currently open call.",
    benefits: ["Up to 70% support for qualifying costs on eligible calls", "International R&D partner collaboration"],
    funding: { min: 0, max: null, currency: "SGD", asStated: "Up to 70% of qualifying costs; limits vary by call" },
    equityTerms: "No equity stated",
    applicationUrl: "https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/market-access-and-networks/global-innovation-alliance/cip-programmes",
    rolling: true,
    evidence: officialEvidence("https://www.enterprisesg.gov.sg/grow-your-business/innovate-with-us/market-access-and-networks/global-innovation-alliance/cip-programmes", "Co-Innovation Programmes", "Enterprise Singapore", ["ongoing and open calls", "eligibility", "up to 70% support", "application process"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "helix-immersion-programme",
    kind: "program",
    name: "Helix Immersion Programme",
    aliases: ["HIP"],
    programType: "fellowship",
    organizerIds: ["sginnovate"],
    description: "A one-year, full-time biomedical industry fellowship placing qualified Singapore research professionals into fast-growing biotech and medtech companies.",
    publicationState: "published",
    deliveryMode: "onsite",
    locationIds: ["sginnovate-singapore"],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: [],
    sectors: ["biotech", "healthcare", "medtech"],
    stages: ["seed", "series_a", "series_b_plus"],
    eligibility: "Singapore citizens or permanent residents with an eligible MSc or PhD and relevant biomedical research or laboratory experience.",
    benefits: ["Twelve-month industry fellowship", "Mentorship", "Monthly stipend up to SGD 7,000"],
    funding: { min: 0, max: 7000, currency: "SGD", asStated: "Monthly stipend up to SGD 7,000" },
    equityTerms: "No equity stated",
    applicationUrl: "https://www.sginnovate.com/apprenticeship/helix-programme",
    rolling: true,
    evidence: officialEvidence("https://www.sginnovate.com/apprenticeship/helix-programme", "Helix Immersion Programme", "SGInnovate", ["applications open", "eligibility", "twelve-month fellowship", "stipend"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
  {
    id: "powerx-singapore",
    kind: "program",
    name: "PowerX",
    aliases: [],
    programType: "fellowship",
    organizerIds: ["sginnovate"],
    description: "A twelve-month deep-tech traineeship combining structured development, on-the-job experience, mentorship, and possible employment with a participating Singapore company.",
    publicationState: "published",
    deliveryMode: "onsite",
    locationIds: ["sginnovate-singapore"],
    eligibleMarketCodes: ["SG"],
    marketWideCodes: [],
    sectors: ["deeptech", "artificial intelligence", "cybersecurity", "robotics", "climate"],
    stages: ["pre_seed", "seed", "series_a", "series_b_plus"],
    eligibility: "Singapore citizens or permanent residents with a diploma or university degree, preferably in STEM, basic programming skills, and at least one year of full-time work experience.",
    benefits: ["Twelve-month training and company placement", "Mentorship", "Monthly training and stipend support up to SGD 5,000"],
    funding: { min: 0, max: 5000, currency: "SGD", asStated: "Monthly training and stipend support up to SGD 5,000" },
    equityTerms: "No equity stated",
    applicationUrl: "https://www.sginnovate.com/power-x-talent",
    rolling: true,
    evidence: officialEvidence("https://www.sginnovate.com/power-x-talent", "PowerX Talent", "SGInnovate", ["apply-now path", "eligibility", "twelve-month traineeship", "stipend"]),
    lastVerifiedAt: CHECKED_AT,
    nextReviewAt: PROGRAM_REVIEW_AT,
  },
];

const organizations = JSON.parse(readFileSync(organizationsPath, "utf8")) as EcosystemOrganization[];
const programs = JSON.parse(readFileSync(programsPath, "utf8")) as EcosystemProgram[];
const organizationIds = new Set(organizations.map((item) => item.id));
const programIds = new Set(programs.map((item) => item.id));
for (const organization of organizerSeeds) {
  if (!organizationIds.has(organization.id)) organizations.push(organization);
}
for (const program of programSeeds) {
  if (!programIds.has(program.id)) programs.push(program);
}
organizations.sort((a, b) => a.name.localeCompare(b.name));
programs.sort((a, b) => a.name.localeCompare(b.name));
writeFileSync(organizationsPath, `${JSON.stringify(organizations, null, 2)}\n`);
writeFileSync(programsPath, `${JSON.stringify(programs, null, 2)}\n`);
console.log(`Resolved two MAS leads and ten remaining Startup SG programme leads (${programSeeds.length} programmes published; two non-opportunities excluded by the manifest).`);
